<a href="https://colab.research.google.com/github/Tushar981/Full-Stack-Data-Science-Assignment/blob/main/1_21_2023.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
arr=np.ones((3,4))
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [5]:
arr+5

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [7]:
arr*5*5

array([[25., 25., 25., 25.],
       [25., 25., 25., 25.],
       [25., 25., 25., 25.]])

In [12]:
## It will give us random value array
np.empty((3,4))
np.empty((3,4),int)

array([[4627730092099895296, 4627730092099895296, 4627730092099895296,
        4627730092099895296],
       [4627730092099895296, 4627730092099895296, 4627730092099895296,
        4627730092099895296],
       [4627730092099895296, 4627730092099895296, 4627730092099895296,
        4627730092099895296]])

In [17]:
# This will give us n number of identity matrix
np.eye(5)
np.eye(5,dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [19]:
# Optional
import pandas as pd
pd.DataFrame(arr)

0    1    2    3
0  1.0  1.0  1.0  1.0
1  1.0  1.0  1.0  1.0
2  1.0  1.0  1.0  1.0

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  from matplotlib import pyplot as plt
  import seaborn as sns
  palette = list(sns.palettes.mpl_palette('Dark2'))
  counted = (series[0]
                .value_counts()
              .reset_index(name='counts')
              .rename({'index': 0}, axis=1)
              .sort_values(0, ascending=True))
  xs = counted[0]
  ys = counted['counts']
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_0.sort_values(0, ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel(0)
_ = plt.ylabel('count()')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  from matplotlib import pyplot as plt
  import seaborn as sns
  palette = list(sns.palettes.mpl_palette('Dark2'))
  counted = (series[1]
                .value_counts()
              .reset_index(name='counts')
              .rename({'index': 1}, axis=1)
              .sort_values(1, ascending=True))
  xs = counted[1]
  ys = counted['counts']
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_1.sort_values(1, ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel(1)
_ = plt.ylabel('count()')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  from matplotlib import pyplot as plt
  import seaborn as sns
  palette = list(sns.palettes.mpl_palette('Dark2'))
  counted = (series[2]
                .value_counts()
              .reset_index(name='counts')
              .rename({'index': 2}, axis=1)
              .sort_values(2, ascending=True))
  xs = counted[2]
  ys = counted['counts']
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_2.sort_values(2, ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel(2)
_ = plt.ylabel('count()')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  from matplotlib import pyplot as plt
  import seaborn as sns
  palette = list(sns.palettes.mpl_palette('Dark2'))
  counted = (series[3]
                .value_counts()
              .reset_index(name='counts')
              .rename({'index': 3}, axis=1)
              .sort_values(3, ascending=True))
  xs = counted[3]
  ys = counted['counts']
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_3.sort_values(3, ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel(3)
_ = plt.ylabel('count()')

In [23]:
import random
random.choice((1,2,3,4,5,6))


2

In [25]:
random.choice("Tushar")

'h'

In [ ]:
random.choice(("Tushar")

In [28]:
random.randrange(1,1000)


431

In [31]:
# here we can get any number between 0 (included ) to 1(excluded)
random.random()

0.9680207809100254

In [36]:
list=[1,2,3,4,5,6,7,8,9,10]
random.shuffle(list)

In [37]:
random.uniform(7,14) # a no will repeat between 7 and 14

9.39154623006167

In [38]:
np.random.rand(1)

array([0.82072161])

In [39]:
np.random.rand(2,3)

array([[0.71394145, 0.6431058 , 0.35856431],
       [0.22500573, 0.54533295, 0.68208578]])

In [40]:
np.random.randn(2,3)

array([[-0.75498486, -0.33714146,  1.04806858],
       [ 0.68248619, -2.06882401, -0.88108381]])

In [41]:
np.random.random_sample()

0.35568325172173565

In [42]:
np.random.randint(1,5,size=(3,4))

array([[2, 4, 3, 1],
       [2, 4, 3, 2],
       [4, 1, 2, 4]])

In [47]:
arr
arr.size
arr.shape
arr.ndim # it will give how many no of dimensional  we have 2 brackets beacuse of that 2 is comming


2

In [51]:
arr
# array has 12 elements beaucause of that we need to write the 12 multiplication while reshaping the array

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [53]:
arr.reshape(2,6)
arr.reshape(6,2)

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [55]:
# Here we are giving only row not column thing so computer will automatically understand what will be the number so in that case u need to writ the -1
# u can use this concept in the vice versa in row
arr.reshape(4,-1)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [56]:
arr.reshape(-1,4)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [63]:
# while doing the reshape it is doing shallow copy how we can check
arr.reshape(2,6).base

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [64]:
arr.reshape(2,2,3)
# First 2 is 2 times
# Second 2 is Row
# Third 3 will be column

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [67]:
arr.reshape(4,3,1)

array([[[1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.]]])

In [85]:
# Creating the different dimensions array
arr1=np.zeros(2)
arr1

array([0., 0.])

In [74]:

arr2=np.zeros((3,4))
arr2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [75]:
arr3=np.zeros((1,3,4)) # 3 Rows and 4 Colums + 1 Dimensions
arr3

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [76]:
arr4=np.zeros((2,3,4))
arr4

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [88]:
arr1=np.random.randint(1,10,(5,6))
arr1

array([[3, 5, 2, 9, 8, 6],
       [7, 2, 2, 3, 2, 9],
       [9, 2, 1, 4, 3, 4],
       [1, 1, 1, 4, 5, 7],
       [5, 9, 6, 8, 8, 3]])

In [80]:
arr1>5 # this will provide the boolean answer

array([[ True, False,  True, False, False,  True],
       [False, False, False,  True, False, False],
       [False, False, False,  True,  True,  True],
       [ True,  True, False, False, False,  True],
       [ True,  True, False, False,  True, False]])

In [81]:
## Now i want to filtter the elements using some condition
arr1[arr1>5]

array([7, 8, 8, 6, 6, 8, 8, 8, 6, 6, 6, 9, 7])

In [86]:
arr1[arr1<5]

array([0., 0.])

In [89]:
arr1


array([[3, 5, 2, 9, 8, 6],
       [7, 2, 2, 3, 2, 9],
       [9, 2, 1, 4, 3, 4],
       [1, 1, 1, 4, 5, 7],
       [5, 9, 6, 8, 8, 3]])

In [90]:
arr1[2:5,0:2] # Slicing  it means it will provide u the continue manner like 0 and 1 index

array([[9, 2],
       [1, 1],
       [5, 9]])

In [91]:
arr1[2:5,[0,2]] # here we get the specific the index like 0 and 2 index

array([[9, 1],
       [1, 1],
       [5, 6]])

In [93]:
arr1[[2,4]] # here we get the specific Rows

array([[9, 2, 1, 4, 3, 4],
       [5, 9, 6, 8, 8, 3]])

In [95]:
arr1[2:4] # with the help we get the result in continuous manner

array([[9, 2, 1, 4, 3, 4],
       [1, 1, 1, 4, 5, 7]])

In [96]:
arr1[2:4,[1,3]]

array([[2, 4],
       [1, 4]])

In [107]:
arr1 =np.random.randint(1,3,(3,3))
arr2 =np.random.randint(1,3,(3,3))
arr1
arr2

array([[1, 1, 2],
       [2, 1, 1],
       [1, 1, 2]])

In [108]:
arr1+arr2
arr1-arr2
arr1*arr2


array([[2, 1, 4],
       [4, 2, 1],
       [1, 2, 4]])

In [110]:
# matrix multiplcation
arr1 @ arr2

#arr1 => M X N
#arr 2 => P X Q

# Matrix multiplication is only possible whenever we have N X P should be equal

array([[6, 5, 9],
       [7, 5, 8],
       [7, 5, 8]])

In [111]:
arr1 /arr2 # index wise dividation

array([[2., 1., 1.],
       [1., 2., 1.],
       [1., 2., 1.]])

In [112]:
arr1/0

<ipython-input-112-2e1dc0d9289f>:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [113]:
arr1

array([[2, 1, 2],
       [2, 2, 1],
       [1, 2, 2]])

In [118]:
# Broadcasting the thing
new =np.zeros((4,4))
new

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [123]:
new1=np.array([1,2,3,4]) # we define the 4 column cause where we are using this in that place the 4 columns are there
new1

array([1, 2, 3, 4])

In [129]:
new + new1 # this will add new 1 array to the new array

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [ ]:
# Transpose



In [126]:
np.sqrt(arr1)

array([[1.41421356, 1.        , 1.41421356],
       [1.41421356, 1.41421356, 1.        ],
       [1.        , 1.41421356, 1.41421356]])

In [127]:
np.max(arr1)

2

In [128]:
arr1.T

array([[2, 2, 1],
       [1, 2, 2],
       [2, 1, 2]])

In [134]:
#expand_dims >> expands the array by inserting  a new axis
#use case -> it helps in image processing
# axis =0 means rows
# axis =1 means column
arr=np.array([[1,2,3],[4,5,6],[1,2,3]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3]])

In [135]:
np.sum(arr)

27

In [136]:
np.sum(arr,axis=0) # witb the help the sum is comming in the row  wise
#1+4+1 ->6
#2+5+2 ->9
#3+6+3 ->12

array([ 6,  9, 12])

In [138]:
np.sum(arr,axis=1)# witb the help the sum is comming in the column  wise
#1+2+3 ->6
#4+5+6 ->15
#1+2+3 ->6

array([ 6, 15,  6])

In [141]:
new_array=np.array([1,2,3,4])
new_array

array([1, 2, 3, 4])

In [143]:
# Whatever array u passed in that it will add 1 dimension
# if it is 1 then 2 or if it is 2 it will be 3
# so here row wise dimension increase
new_array1=np.expand_dims(new_array,axis=0)
new_array1

array([[1, 2, 3, 4]])

In [144]:
new_array2=np.expand_dims(new_array1,axis=0)
new_array2

array([[[1, 2, 3, 4]]])

In [147]:
test1=np.zeros((3,4))
test1

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [148]:
test2=np.expand_dims(test1,axis=1)
test2

array([[[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]]])